name: 'DogeCloud COS Action'
description: 'Upload files to DogeCloud COS'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  access_key:
    description: 'DogeCloud access key. Should be referred to a encrypted environment variable'
    required: true
  secret_key:
    description: 'DogeCloud secret key. Should be referred to a encrypted environment variable'
    required: true
  bucket:
    description: 'COS bucket name'
    required: true
  region:
    description: 'COS bucket region'
    required: true
  local_path:
    description: 'Local path to be uploaded to COS. Directory or file is allowed'
    required: true
  remote_path:
    description: 'COS path to put the local files in on COS'
    required: true
  clean:
    description: 'Set to true for cleaning files on COS path which are not existed in local path. Default is false'
    required: false
  accelerate:
    description: 'Set to true for using accelerate domain to upload files. Default is false'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
